#
# This file is autogenerated by pip-compile
# To update, run:
#
#    pip-compile --output-file=requirements.txt requirements.in
#
appdirs==1.4.3            # via -r requirements.in, black
attrs==19.3.0             # via -r requirements.in, black
black==19.10b0            # via -r requirements.in
certifi==2019.11.28       # via -r requirements.in, requests
chardet==3.0.4            # via -r requirements.in, requests
click==7.1.1              # via -r requirements.in, black, pip-tools
entrypoints==0.3          # via -r requirements.in, flake8
flake8==3.7.9             # via -r requirements.in
idna==2.9                 # via -r requirements.in, requests
mccabe==0.6.1             # via -r requirements.in, flake8
pathspec==0.7.0           # via -r requirements.in, black
pip-tools==4.5.1          # via -r requirements.in
pycodestyle==2.5.0        # via -r requirements.in, flake8
pyflakes==2.1.1           # via -r requirements.in, flake8
regex==2020.2.20          # via -r requirements.in, black
requests==2.23.0          # via -r requirements.in, robin-stocks
robin-stocks==1.0.0.2     # via -r requirements.in
six==1.14.0               # via -r requirements.in, pip-tools
tabulate==0.8.6           # via -r requirements.in
toml==0.10.0              # via -r requirements.in, black
typed-ast==1.4.1          # via -r requirements.in, black
urllib3==1.25.8           # via -r requirements.in, requests
